config/routes.rb
Rails.application.routes.draw do

  get 'campaigns',                             :controller => :campaigns, :action => :summary
  get 'campaigns/summary',       as: :summary, :controller => :campaigns, :action => :summary
  get 'campaigns/:name/details', as: :details, :controller => :campaigns, :action => :details

  root 'campaigns#summary'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def summary
    @campaigns = Campaign.select(:name).group(:name).order(:name).sum(:score)
  end

  def details
    @campaigns = Campaign.where(:name => params[:name]).order(:candidate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/details.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Candidate</th>
    <th>Score</th>
    <th>Invalid score</th>
  </tr>
  </thead>

  <tbody>
  <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.name %></td>
        <td><%= campaign.candidate %></td>
        <td><%= campaign.score %></td>
        <td><%= campaign.invalid_score %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', summary_path %>

app/views/campaigns/summary.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns summary</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Score</th>
  </tr>
  </thead>

  <tbody>
  <% @campaigns.each do |campaign, score| %>
      <tr>
        <td><%= link_to campaign, details_path(campaign) %></td>
        <td><%= score %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssessmentBb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>